data:
  xlsx_path: data/dialogs.xlsx
  col_id: "Id звонка"
  col_text: "Текст транскрибации"

filters:
  min_call_secs: 180
  require_client_evidence: true
  rare_threshold: 3
  warn_small_D_threshold: 50

retrieval:
  top_k: 8

llm:
  use_openai: true
  model_id_extraction: gpt-4o-mini
  model_id_labeling: gpt-4o-mini
  model_id_summary: gpt-4o-mini
  temperature: 0.2
  top_p: 0.9
  seed: 7

report:
  show_ids_in_card_limit: 20
  require_client_role_for_ideas: true
  show_operator_recos_section: true
  per_dialog_counts: true
