name: DoD QA
on: [push, pull_request]
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install duckdb pandas numpy umap-learn hdbscan jinja2
      - run: make qa
      - run: make eval
